name: Hello, world!
on: 
  push:
    branches: [master]

jobs:
  build:
    name: Greeting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
      - run: npm install
      - name: Translate secrets of base64 into json
        env:
          JSON_DECODE: ${{ secrets.JSON_CREDENTIAL }}
        run: echo -n $JSON_DECODE | base64 --decode > ./gcloud-key.json
      - name: \@serverless/cli install
        run: npm install -g @serverless/cli
      - name: Deploy
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: npm run deploy:prod